name: Build snapshot version and upload to Maven Central

on:
  push:
    branches: ["master"]

permissions: {}

jobs:
  call-snapshot-job:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@646d9b629925d6405fb06ed1476aefd6b2cdca86 # v0.0.23
    with:
      java_version: "11"
      project_name: "Commonjava/atlas"
      snapshot_deploy_command: "mvn help:effective-settings -B -V clean deploy -e"
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_BOT_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_BOT_TOKEN }}
